# Generated by Django 5.1.7 on 2025-04-13 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_challenge_achievement_goalprogress_meal_nutritionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
