# Generated by Django 5.1.7 on 2025-04-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_exercise_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalprogress',
            options={'ordering': ['-date']},
        ),
    ]
