# Generated by Django 5.1.7 on 2025-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exercise_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_log'),
        ),
    ]
