# Generated by Django 5.1.7 on 2025-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dailylog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nutritionlog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_nutrition_log_per_day'),
        ),
    ]
