# Generated by Django 5.1.7 on 2025-04-23 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_nutritionlog_unique_nutrition_log_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
