# Generated by Django 5.1.7 on 2025-04-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_challenge_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userchallenge',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_challenge'),
        ),
    ]
