# Generated by Django 5.1.7 on 2025-04-23 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userchallenge_unique_user_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='userreport',
            constraint=models.UniqueConstraint(fields=('user', 'report_date'), name='unique_user_report_date'),
        ),
    ]
