# Generated by Django 5.1.7 on 2025-04-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_userreport_report_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutplan',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_workout_plan'),
        ),
    ]
