# Generated by Django 5.1.7 on 2025-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_workoutplan_unique_user_workout_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
