# Generated by Django 5.1.7 on 2025-05-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_exercise_notes_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
