# Generated by Django 5.1.7 on 2025-05-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
