# Generated by Django 5.1.7 on 2025-05-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_meal_date_meal_meal_type_meal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='water_amount',
            field=models.FloatField(blank=True, help_text='Liters of water consumed', null=True),
        ),
    ]
