# Generated by Django 5.1.7 on 2025-05-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeplog',
            name='bedtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='wake_feeling',
            field=models.CharField(blank=True, choices=[('refreshed', 'Refreshed'), ('tired', 'Tired'), ('okay', 'Okay')], max_length=50),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='wake_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
