# Generated by Django 5.1.7 on 2025-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
