# Generated by Django 5.1.7 on 2025-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_notification_sleepschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='last_known_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
