# Generated by Django 5.1.7 on 2025-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userchallenge_last_known_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
