# Generated by Django 5.1.7 on 2025-05-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_customuser_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='exercises',
        ),
        migrations.CreateModel(
            name='DailyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('activity', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_workouts', to='api.workoutplan')),
            ],
        ),
    ]
