# Generated by Django 5.1.7 on 2025-05-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_workoutplan_exercises_dailyworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prefers_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
