# Generated by Django 5.1.7 on 2025-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_customuser_prefers_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unit_preferences',
            field=models.JSONField(default=dict, help_text="User's unit preferences for measurements."),
        ),
    ]
