# Generated by Django 5.1.7 on 2025-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_customuser_unit_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link for more details.', null=True),
        ),
    ]
