# Generated by Django 5.1.7 on 2025-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='auto_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
