# Generated by Django 5.1.7 on 2025-06-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_workoutplan_auto_repeat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
