# Generated by Django 5.1.7 on 2025-06-07 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
