# Generated by Django 5.1.7 on 2025-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userchallenge_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_known_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
