# Generated by Django 5.1.7 on 2025-06-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_customuser_last_known_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_known_rank',
        ),
    ]
