# Generated by Django 5.1.7 on 2025-06-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_challenge_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
    ]
